### ISSUE TITLE
The picture does not show

### ISSUE THREAD

**Issue by oops-lgtm** [AmazingRise/hugo-theme-diary#100]
我从其他主题迁移到`diary`，发现文章的图片都不能显示。

我使用的是`typora`编辑器。`typora`中调整图片大小，会将格式`![]()`改为`<img src="https://..." style="zoom:50%;" />`。
将图片格式换回`![]()`后能正确显示。

看了[wiki](https://github.com/AmazingRise/hugo-theme-diary/wiki/Inserting-Figures)，感觉对所有的图片进行调整有点麻烦。

问，能否支持`<img src="https://..." style="zoom:50%;" />`来进行resize？

不太懂前端的技术，如果这个问题问得比较蠢，请勿介意。

**Comment by oops-lgtm** [comment]
config.toml中配置
```toml
[markup.goldmark.renderer]
    unsafe = true
```
即可
