### ISSUE TITLE
error calling Paginator: pagination not supported for this page

### ISSUE THREAD

**Issue by LinkSake** [AmazingRise/hugo-theme-diary#177]
**Describe the bug**
In a newly created Hugo project, with just the `hugo.toml` modified, after creating a post an error will rise:

```
Failed to render "/posts/post-1/": render: failed to render pages: render of "page" failed: [1;36m"/Users/angel/Documents/spicer/themes/diary/layouts/_default/baseof.html:15:16"[0m: execute of template failed at <partial "extrabar.html" .>: error calling partial: [1;36m"/Users/angel/Documents/spicer/themes/diary/layouts/partials/extrabar.html:28:19"[0m: execute of template failed at <.Paginator>: error calling Paginator: pagination not supported for this page: kind: "page", path: "/posts/post-1", file: "/Users/angel/Documents/spicer/content/posts/post-1.md" 
```

**To Reproduce**

1. I have only one post, a clone of `exampleSite/content/posts/post-1.md`

2. `hugo.toml`:

```toml
baseURL = 'https://example.org/'
DefaultContentLanguage= 'es'
languageCode = 'es-mx'
title = 'Foo'
theme = 'diary'
copyright = 'Foo'

[params]
   subtitle = 'Foo'
   enableReadingTime=true   
   disableToC=true

[taxonomies]
   category = "categories"
   tag = "tags"

[[menu.main]]
   url = "/posts"
   name = "Archivo"
   weight = 1
[[menu.main]]
   url = "/categories"
   name = "Categorias"
   weight = 2
[[menu.main]]
   url = "/tags"
   name = "Tags"
   weight = 3
```

**Expected behavior**

Hugo project should not have an issue running.

**Screenshots**

![Screenshot 2024-02-21 at 14 50 52](https://github.com/AmazingRise/hugo-theme-diary/assets/24723752/f8ba8c0b-d7ed-471e-b4d6-12100fb8f85f)

**Environment**

* **Hugo**: hugo v0.123.1-3f8434a62fc91a50f4e5bd43a4435d2d301844ff+extended darwin/arm64 BuildDate=2024-02-21T08:17:45Z VendorInfo=brew
* **Browser**: Brave v 1.62.165

**Additional context**

Removing `{{- partial "extrabar.html" . -}}` and `{{- partial "mobile-footer.html" . -}}` from `themes/diary/layouts/_default/baseof.html` solves the issue, but this will take funcionality out.
