### ISSUE TITLE
blog里面修改图片大小

### ISSUE THREAD

**Issue by Victorfy** [AmazingRise/hugo-theme-diary#24]
请问如何在blog markdown文件中修改添加的图片大小？比如宽度和长度都变为1/2。
谢谢

**Comment by AmazingRise** [comment]
这个可能需要写 HTML 来实现：
参考 https://discourse.gohugo.io/t/how-customise-image-size-in-md-files/4529/19

**Comment by Victorfy** [comment]
看了一下感觉不太明白

**Comment by AmazingRise** [comment]
> 看了一下感觉不太明白

就是直接在 markdown 里面写 HTML 代码
```html
<img src="图片路径" width=50% />
```

**Comment by Victorfy** [comment]
@AmazingRise 试过了，不行

**Comment by AmazingRise** [comment]
不行具体是指什么？
如果是完全显示不出图片，请在你的网站的`config.toml`添加以下内容
```toml
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = true
```
在我这边是完全没问题的
