### ISSUE TITLE
分类和标签无显示

### ISSUE THREAD

**Issue by guyueshui** [AmazingRise/hugo-theme-diary#9]
你好，我非常喜欢这个主题，感谢你做的移植工作。但是我在配置过程中遇到一个问题，就是分类页和标签页没有东西显示。我看了你的文档，分类确实只用了一个值，没有用括号括起来，但还是空白，请问如何解决？
![screenshot-20200316-00-16-33](https://user-images.githubusercontent.com/12670826/76705588-2e321200-671c-11ea-92fd-de6ebc1f6b49.png)

**Comment by AmazingRise** [comment]
不太确定你的问题出在哪里，但是应该可以排除Taxonomies的设置问题
因为如果没有设置Taxonomies的话，会出现 404.

不如你贴一下你的每个 Post 的 Metadata 区是怎么写的？
[Example here](https://github.com/AmazingRise/hugo-theme-diary/wiki/Post's-meta-data)

**Comment by AmazingRise** [comment]
暂时无法复现出这个问题。
建议检查一下：
1. 你是否正确配置了[Taxonomies](https://github.com/AmazingRise/hugo-theme-diary/wiki/Taxonomies-and-Sections-(Archive,-Categories-and-Tags)#taxonomies)
2. 另外请劳烦您提供一下某篇博文的 Frontmatter 区。（一篇就够

**Comment by guyueshui** [comment]
> 暂时无法复现出这个问题。
> 建议检查一下：
> 
> 1. 你是否正确配置了[Taxonomies](https://github.com/AmazingRise/hugo-theme-diary/wiki/Taxonomies-and-Sections-(Archive,-Categories-and-Tags)#taxonomies)
> 2. 另外请劳烦您提供一下某篇博文的 Frontmatter 区。（一篇就够

你好，我的配置文件如下：
```toml
# hugo site config
baseurl = "https://guyueshui.github.io/yukynn"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "Yukynnの窝"
theme = "diary"

# copyright = ""

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

# baseURL = "https://guyueshui.github.io/yukynn"
# preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
footnoteReturnLinkContents = "↩"
hasCJKLanguage = true


[params]
  subtitle="子在川上曰，逝者如斯夫。"
  # background = "#f8f8f5"

  author = "Yukynn"
  description = "Yukynn's showcase"

  siteStartYear = 2020

  # paginate of archives, tags and categories             # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
  # archivePaginate = 15

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "January 2, 2006"


[blackfriday]
  # translate new line into linebreaks
  # extensions = ["hardLineBreak"]
  smartypants = false


[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  url = "/posts"
  name = "文章"
  weight = 1
[[menu.main]]
  url = "/categories"
  name = "分类"
  weight = 2
[[menu.main]]
  url = "/tags"
  name = "标签"
  weight = 3
[[menu.main]]
  url = "/about"
  name = "关于"
  weight = 4
[[menu.main]]
  url = "/index.xml"
  name = "订阅"
  weight = 5
```
昨天刚开始建站，从我的博客里拷了几篇文章来，frontmatter如下：
```yaml
---
title: Hello World
date: 2020-03-11T20:50:39+08:00
lastmod: 2020-03-11T20:50:39+08:00
categories: "cat1"
tags: ["tag1", "tag2"]
featured_image: "/artworks/bilibilier.jpg"
description: 你好世界，愿这里成为你的一片净土。
---
```
上面这个是hello-world, 我也从我之前博客里复制了几篇过来，frontmatter可能不一样，但仅仅只是date format的区别。
